import "./globals.css";
import { Inter } from "next/font/google";
import Provider from "@/utils/provider";
import WebSocketProvider from "@/utils/websocket_provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Socius",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <WebSocketProvider>{children}</WebSocketProvider>
        </Provider>
      </body>
    </html>
  );
}
